import type { Phase } from "./devocional.server";
export const phases: Phase[] = [
  {
    n: 1,
    name: "O ESPELHO",
    range: "DIAS 01–15",
    question: "Quem você realmente é quando para de justificar tudo?",
    days: [1, 15],
  },
  {
    n: 2,
    name: "O CORTE",
    range: "DIAS 16–30",
    question: "O que precisa sair da sua vida para que Deus possa trabalhar em você?",
    days: [16, 30],
  },
  {
    n: 3,
    name: "O DESERTO",
    range: "DIAS 31–45",
    question: "Você ainda confia em Deus quando não entende o que Ele está fazendo?",
    days: [31, 45],
  },
  {
    n: 4,
    name: "A CURA",
    range: "DIAS 46–60",
    question: "Você quer realmente ser curado ou apenas aprender a conviver com a ferida?",
    days: [46, 60],
  },
  {
    n: 5,
    name: "A MUDANÇA",
    range: "DIAS 61–75",
    question: "Se você realmente mudou, onde isso está aparecendo nas suas escolhas?",
    days: [61, 75],
  },
  {
    n: 6,
    name: "NÃO VOLTE A SER QUEM ERA",
    range: "DIAS 76–90",
    question: "Depois de tudo que Deus mostrou a você, quem você vai escolher ser?",
    days: [76, 90],
  },
];
export const days = [
  { n: 1, phase: 1, title: "ATÉ QUANDO?" },
  { n: 2, phase: 1, title: "A DESCULPA TAMBÉM É UMA ESCOLHA" },
  { n: 3, phase: 1, title: "VOCÊ NÃO É A VÍTIMA DE TODAS AS HISTÓRIAS" },
  { n: 4, phase: 1, title: "O ORGULHO NÃO PARECE ORGULHO" },
  { n: 5, phase: 1, title: "VOCÊ ESTÁ TENTANDO CONTROLAR DEUS?" },
  { n: 6, phase: 1, title: "QUEM VOCÊ É QUANDO NINGUÉM ESTÁ OLHANDO?" },
  { n: 7, phase: 1, title: "PARE DE SE COMPARAR" },
  { n: 8, phase: 1, title: "NEM TODO “SIM” É OBEDIÊNCIA" },
  { n: 9, phase: 1, title: "VOCÊ ESTÁ CANSADO OU DESALINHADO?" },
  { n: 10, phase: 1, title: "VOCÊ ESTÁ ALIMENTANDO AQUILO QUE QUER MATAR?" },
  { n: 11, phase: 1, title: "VOCÊ ESTÁ ESPERANDO SENTIR VONTADE?" },
  { n: 12, phase: 1, title: "PARE DE FUGIR DAS CONVERSAS NECESSÁRIAS" },
  { n: 13, phase: 1, title: "VOCÊ NÃO PRECISA TER RAZÃO O TEMPO TODO" },
  { n: 14, phase: 1, title: "O QUE VOCÊ TEM TOLERADO?" },
  { n: 15, phase: 1, title: "OLHE NO ESPELHO" },
  { n: 16, phase: 2, title: "PERDOAR NÃO É DIZER QUE NÃO DOEU" },
  { n: 17, phase: 2, title: "VOCÊ ESTÁ GUARDANDO MÁGOA COMO SE FOSSE JUSTIÇA?" },
  { n: 18, phase: 2, title: "PARE DE PEDIR APROVAÇÃO" },
  { n: 19, phase: 2, title: "NEM TODO RELACIONAMENTO PRECISA CONTINUAR" },
  { n: 20, phase: 2, title: "PARE DE ALIMENTAR A CULPA" },
  { n: 21, phase: 2, title: "VOCÊ ESTÁ TENTANDO SER FORTE O TEMPO TODO?" },
  { n: 22, phase: 2, title: "O DINHEIRO REVELA MAIS DO QUE VOCÊ PENSA" },
  { n: 23, phase: 2, title: "VOCÊ ESTÁ TENTANDO PROVAR ALGUMA COISA?" },
  { n: 24, phase: 2, title: "PARE DE NEGOCIAR COM O QUE SABE SER ERRADO" },
  { n: 25, phase: 2, title: "O QUE VOCÊ CONSOME ESTÁ CONSUMINDO VOCÊ?" },
  { n: 26, phase: 2, title: "PARE DE VIVER PARA SER VISTO" },
  { n: 27, phase: 2, title: "VOCÊ ESTÁ FUGINDO DO SILÊNCIO?" },
  { n: 28, phase: 2, title: "VOCÊ NÃO PRECISA RESPONDER TUDO" },
  { n: 29, phase: 2, title: "CORTE O QUE ESTÁ MATANDO SUA PAZ" },
  { n: 30, phase: 2, title: "O CORTE DÓI ANTES DE CICATRIZAR" },
  { n: 31, phase: 3, title: "QUANDO DEUS PARECE SILENCIOSO" },
  { n: 32, phase: 3, title: "VOCÊ QUER O PROCESSO OU SÓ O RESULTADO?" },
  { n: 33, phase: 3, title: "ESPERAR TAMBÉM É FAZER ALGUMA COISA" },
  { n: 34, phase: 3, title: "PORTA FECHADA NÃO É FRACASSO" },
  { n: 35, phase: 3, title: "NÃO DESISTA NO MEIO" },
  { n: 36, phase: 3, title: "QUANDO VOCÊ NÃO ENTENDER" },
  { n: 37, phase: 3, title: "O DESERTO NÃO É SUA CASA" },
  { n: 38, phase: 3, title: "PARE DE COMPARAR SEU TEMPO" },
  { n: 39, phase: 3, title: "A FÉ NÃO PRECISA DE GARANTIAS" },
  { n: 40, phase: 3, title: "QUANDO VOCÊ SE SENTIR SOZINHO" },
  { n: 41, phase: 3, title: "NÃO TOME DECISÕES DEFINITIVAS EM MOMENTOS TEMPORÁRIOS" },
  { n: 42, phase: 3, title: "QUANDO NINGUÉM RECONHECE" },
  { n: 43, phase: 3, title: "O QUE O DESERTO ESTÁ ENSINANDO?" },
  { n: 44, phase: 3, title: "VOCÊ AINDA CONFIA?" },
  { n: 45, phase: 3, title: "VOCÊ NÃO CHEGOU ATÉ AQUI POR ACASO" },
  { n: 46, phase: 4, title: "A FERIDA NÃO PODE VIRAR SUA IDENTIDADE" },
  { n: 47, phase: 4, title: "PARE DE SE PUNIR" },
  { n: 48, phase: 4, title: "DEUS NÃO DESPERDIÇA FERIDAS" },
  { n: 49, phase: 4, title: "PARE DE VOLTAR AO LUGAR QUE TE MACHUCOU" },
  { n: 50, phase: 4, title: "A CURA TAMBÉM EXIGE TEMPO" },
  { n: 51, phase: 4, title: "NÃO ESCONDA O QUE PRECISA SER TRATADO" },
  { n: 52, phase: 4, title: "VOCÊ AINDA ESTÁ TENTANDO MERECER O AMOR DE DEUS?" },
  { n: 53, phase: 4, title: "NÃO CONFUNDA CASTIGO COM CONSEQUÊNCIA" },
  { n: 54, phase: 4, title: "VOCÊ PRECISA DE CURA OU DE VINGANÇA?" },
  { n: 55, phase: 4, title: "NÃO TENHA VERGONHA DE RECOMEÇAR" },
  { n: 56, phase: 4, title: "SUA HISTÓRIA NÃO TERMINOU NO PIOR CAPÍTULO" },
  { n: 57, phase: 4, title: "DEUS TAMBÉM CURA ATRAVÉS DE PESSOAS" },
  { n: 58, phase: 4, title: "NÃO VOLTE PARA O QUE DEUS TE TIROU" },
  { n: 59, phase: 4, title: "A CURA MUDA SUAS ESCOLHAS" },
  { n: 60, phase: 4, title: "AGORA OLHE PARA TRÁS" },
  { n: 61, phase: 5, title: "AGORA FAÇA ALGUMA COISA" },
  { n: 62, phase: 5, title: "DISCIPLINA É FAZER DE NOVO" },
  { n: 63, phase: 5, title: "NÃO CONFIE APENAS NA SUA FORÇA DE VONTADE" },
  { n: 64, phase: 5, title: "ORGANIZE O QUE ESTÁ DESORGANIZADO" },
  { n: 65, phase: 5, title: "APRENDA A TERMINAR" },
  { n: 66, phase: 5, title: "SEJA FIEL NO PEQUENO" },
  { n: 67, phase: 5, title: "PARE DE ESPERAR PERMISSÃO" },
  { n: 68, phase: 5, title: "SUA BOCA TAMBÉM CONSTRÓI OU DESTRÓI" },
  { n: 69, phase: 5, title: "NÃO TRANSFORME CANSAÇO EM DESISTÊNCIA" },
  { n: 70, phase: 5, title: "O QUE VOCÊ ESTÁ CONSTRUINDO?" },
  { n: 71, phase: 5, title: "SEJA A MESMA PESSOA EM TODOS OS LUGARES" },
  { n: 72, phase: 5, title: "APRENDA A DIZER “EU ERREI”" },
  { n: 73, phase: 5, title: "NÃO ABANDONE SUA CASA PARA CONSTRUIR SUA IMAGEM" },
  { n: 74, phase: 5, title: "FAÇA O CERTO QUANDO FOR MAIS CARO" },
  { n: 75, phase: 5, title: "A MUDANÇA PRECISA CONTINUAR" },
  { n: 76, phase: 6, title: "NÃO VOLTE" },
  { n: 77, phase: 6, title: "GUARDE SEU CORAÇÃO" },
  { n: 78, phase: 6, title: "NÃO DEIXE O PASSADO VIRAR DESCULPA" },
  { n: 79, phase: 6, title: "VOCÊ AINDA TEM ALGO A APRENDER" },
  { n: 80, phase: 6, title: "NÃO PERCA SUA SENSIBILIDADE" },
  { n: 81, phase: 6, title: "USE SUA HISTÓRIA PARA SERVIR" },
  { n: 82, phase: 6, title: "NÃO TROQUE PROPÓSITO POR APLAUSO" },
  { n: 83, phase: 6, title: "NÃO TENHA MEDO DE MUDAR DE ROTA" },
  { n: 84, phase: 6, title: "SUA VIDA PRECISA CABER NA SUA FÉ" },
  { n: 85, phase: 6, title: "NÃO PERCA A GRATIDÃO" },
  { n: 86, phase: 6, title: "VOCÊ NÃO PRECISA CORRER" },
  { n: 87, phase: 6, title: "CONTINUE QUANDO A EMOÇÃO FOR EMBORA" },
  { n: 88, phase: 6, title: "O QUE VOCÊ VAI FAZER COM TUDO ISSO?" },
  { n: 89, phase: 6, title: "VOCÊ NÃO É MAIS QUEM COMEÇOU" },
  { n: 90, phase: 6, title: "AGORA É COM VOCÊ" },
];
export const getPhase = (n: number) => phases.find((p) => p.n === n);
